--Funções Numéricas abs ceil floor mod sqrt power

--ROUND faz o aredondamento
SELECT ROUND(6.75) FROM DUAL; 
SELECT ROUND(6.45) FROM DUAL; 
SELECT ROUND(6.45,0) FROM DUAL; 
SELECT ROUND(6.454678,-1) FROM DUAL; 
SELECT ROUND(6.454678,2) FROM DUAL; 

--TRUNC trunca as posições apos a virgula
SELECT TRUNC(6.75) FROM DUAL; 
SELECT TRUNC(6.75,1) FROM DUAL; 
SELECT TRUNC(6.75,3) FROM DUAL; 


