--Criando e manipulando Indices index

SELECT * FROM USER_INDEXES WHERE INDEX_NAME ='INDICE_EMP_SEQ';
SELECT * FROM EMPLOYEE;
DESCR EMPLOYEE;

CREATE INDEX INDICE_EMP_SEQ ON EMPLOYEE(EMP_SEQ);

DROP INDEX INDICE_EMP_SEQ;