--Criando e manipulando Synonyms 
--Synonyms é um apelido para objetos com nomes longos

SELECT * FROM EMPLOYEE;
SELECT * FROM USER_SYNONYMS;
SELECT * FROM ALL_SYNONYMS;

CREATE SYNONYM EMP FOR EMPLOYEE;  --SÓ SEU USUARIO OU USUARIO DBA VISUALIZAM
CREATE PUBLIC SYNONYM EMP FOR EMPLOYEE;  --TODOS OS USUARIO VISUALIZAM

SELECT * FROM EMP;

DROP SYNONYM EMP;
DROP PUBLIC SYNONYM EMP;