--Criando e manipulando Views

SELECT * FROM EMPLOYEE;
SELECT * FROM USER_VIEWS;
SELECT * FROM ALL_VIEWS;
DROP VIEW EMP;

CREATE VIEW EMP
AS SELECT EMP_SEQ, FNAME FROM EMPLOYEE ORDER BY TO_NUMBER(EMP_SEQ)
;

SELECT * FROM USER_VIEWS;
SELECT * FROM EMP;