--TestandoTrigger com Inserting e Deleting IF

SELECT * FROM VENDA
SELECT * FROM ESTOQUE
INSERT INTO VENDA VALUES (1,1,50)
DELETE VENDA
UPDATE ESTOQUE SET EST_QUANTIDADE = 100;
DROP TRINGGER baixa_estoque

CREATE OR REPLACE TRIGGER baixa_estoque
   AFTER INSERT OR UPDATE OR DELETE OF VEN_QUANTIDADE ON VENDA
   FOR EACH ROW
BEGIN
   IF INSERTING THEN
      UPDATE ESTOQUE 
         SET EST_QUANTIDADE = (EST_QUANTIDADE - :NEW.VEN_QUANTIDADE)
       WHERE EST_CODIGO = :NEW.VEN_CODIGO;
   ELSIF DELETING THEN
      UPDATE ESTOQUE 
         SET EST_QUANTIDADE = (EST_QUANTIDADE + :OLD.VEN_QUANTIDADE)
       WHERE EST_CODIGO = :OLD.VEN_CODIGO;
   END IF;
END baixa_estoque;
