--Criando Tabelas Temporárias
--Tabelas temporárias não aceitam insert e ficam estaticas.

--SELECT * FROM TEMPORARY_ESTOQUE
--DROP TABLE TEMPORARY_ESTOQUE

CREATE GLOBAL TEMPORARY TABLE TEMPORARY_ESTOQUE
ON COMMIT PRESERVE ROWS
AS SELECT * FROM ESTOQUE