--Manipulando Registros type record com select

--set serveroutput ON; 
--SELECT * FROM ESTOQUE
-- DESCR ESTOQUE
DECLARE
   TYPE REGISTRO_ESTOQUE IS RECORD
   (
      CODIGO           NUMBER,
      NOME             VARCHAR2(40),
      TIPO             VARCHAR2(2),
      PRECOVENDA       NUMBER,
      DATACAD          DATE,
      QUANTIDADE       NUMBER   
   );
   DADOS_ESTOQUE REGISTRO_ESTOQUE;
BEGIN
   SELECT * INTO DADOS_ESTOQUE.CODIGO, DADOS_ESTOQUE.NOME, DADOS_ESTOQUE.TIPO, 
                 DADOS_ESTOQUE.PRECOVENDA, DADOS_ESTOQUE.DATACAD, DADOS_ESTOQUE.QUANTIDADE 
     FROM ESTOQUE
    WHERE EST_CODIGO = 3;
   DBMS_OUTPUT.PUT_LINE('Código = ' || TO_CHAR(DADOS_ESTOQUE.CODIGO) || ' nome = ' || DADOS_ESTOQUE.NOME);
END;