--Manipulando Registros com ROWTYPE

--set serveroutput ON; 
--SELECT * FROM ESTOQUE
-- DESCR ESTOQUE
DECLARE
   DADOS_ESTOQUE ESTOQUE%ROWTYPE;
BEGIN
   SELECT * INTO DADOS_ESTOQUE
     FROM ESTOQUE
    WHERE EST_CODIGO = 4;
   DBMS_OUTPUT.PUT_LINE('Código = ' || TO_CHAR(DADOS_ESTOQUE.EST_CODIGO) || ' nome = ' || DADOS_ESTOQUE.EST_NOME);
END;