--PL SQL Iniciando o uso de CURSOR ROWCOUNT

--SELECT * FROM ESTOQUE;

DECLARE
   ID number;
BEGIN
   SELECT EST_CODIGO INTO ID FROM ESTOQUE WHERE EST_CODIGO = 1;
   DBMS_OUTPUT.PUT_LINE('Numero de Registros = ' || TO_CHAR(SQL%ROWCOUNT));
END;