--PL SQL CURSOR com loop NOTFOUND

--SELECT * FROM ESTOQUE;

DECLARE
   CURSOR CURSOR_ESTOQUE IS SELECT * FROM ESTOQUE;
   REGISTRO_ESTOQUE CURSOR_ESTOQUE%ROWTYPE;
BEGIN
   OPEN CURSOR_ESTOQUE;
      LOOP
         FETCH CURSOR_ESTOQUE INTO REGISTRO_ESTOQUE;
         EXIT WHEN CURSOR_ESTOQUE%NOTFOUND;
         DBMS_OUTPUT.PUT_LINE('Codigo = ' || REGISTRO_ESTOQUE.EST_CODIGO || ' nome ' || REGISTRO_ESTOQUE.EST_NOME);
      END LOOP;
   DBMS_OUTPUT.PUT_LINE('Numero de Registros = ' || TO_CHAR(CURSOR_ESTOQUE%ROWCOUNT));
   CLOSE CURSOR_ESTOQUE;
END;